In [1]:
import pandas as pd

# Example DataFrame
data = {'ID': [1, 2, 3, 4],
        'Values': [[1], [], [2, 3], [4, 5, 6]]}

df = pd.DataFrame(data)



In [2]:
df

ID     Values
0   1        [1]
1   2         []
2   3     [2, 3]
3   4  [4, 5, 6]

In [9]:
df[df['Values'].apply(lambda x:x!=[])]

ID     Values
0   1        [1]
2   3     [2, 3]
3   4  [4, 5, 6]

In [10]:
df=df[df['Values'].apply(lambda x:x!=[])]
df

ID     Values
0   1        [1]
2   3     [2, 3]
3   4  [4, 5, 6]

In [17]:
df.iloc[0].ID

1

In [19]:
name=['Sonu Shoo','Mikasa Ackerman']
name

['Sonu Shoo', 'Mikasa Ackerman']

In [20]:
removeSpace=(lambda x:[i.replace(" ","") for i in x])
removeSpace(name)

['SonuShoo', 'MikasaAckerman']

In [22]:
x='ghjtdf hjghg hg'
x.replace(' ','-')

'ghjtdf-hjghg-hg'

In [24]:
import nltk
from nltk.corpus import stopwords


print(stopwords.words('french'))


['au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle', 'en', 'et', 'eux', 'il', 'ils', 'je', 'la', 'le', 'les', 'leur', 'lui', 'ma', 'mais', 'me', 'même', 'mes', 'moi', 'mon', 'ne', 'nos', 'notre', 'nous', 'on', 'ou', 'par', 'pas', 'pour', 'qu', 'que', 'qui', 'sa', 'se', 'ses', 'son', 'sur', 'ta', 'te', 'tes', 'toi', 'ton', 'tu', 'un', 'une', 'vos', 'votre', 'vous', 'c', 'd', 'j', 'l', 'à', 'm', 'n', 's', 't', 'y', 'été', 'étée', 'étées', 'étés', 'étant', 'étante', 'étants', 'étantes', 'suis', 'es', 'est', 'sommes', 'êtes', 'sont', 'serai', 'seras', 'sera', 'serons', 'serez', 'seront', 'serais', 'serait', 'serions', 'seriez', 'seraient', 'étais', 'était', 'étions', 'étiez', 'étaient', 'fus', 'fut', 'fûmes', 'fûtes', 'furent', 'sois', 'soit', 'soyons', 'soyez', 'soient', 'fusse', 'fusses', 'fût', 'fussions', 'fussiez', 'fussent', 'ayant', 'ayante', 'ayantes', 'ayants', 'eu', 'eue', 'eues', 'eus', 'ai', 'as', 'avons', 'avez', 'ont', 'aurai', 'auras', 'aura', 'aurons', 'aur

In [26]:
from nltk.tokenize import word_tokenize

In [27]:
text='This is an example sentence with some stop words.'

In [28]:
stop_words = set(stopwords.words('english'))

In [29]:
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [30]:
word_tokens = word_tokenize(text)
filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]

In [31]:
filtered_text = ' '.join(filtered_sentence)

In [32]:
filtered_text

'example sentence stop words .'

In [33]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [34]:
ps.stem('danced')

'danc'

In [36]:
ps.stem('loved')

'love'

In [37]:
import sklearn

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

In [39]:
cv=CountVectorizer(max_features=50)

In [40]:
sent1 = "Attack on Titan, created by Hajime Isayama, is a gripping anime set in a world besieged by enormous humanoid creatures known as Titans, which have forced humanity to live within massive walled cities for protection."

sent2 = "Death Note is an anime that follows a high school student named Light Yagami who discovers a supernatural notebook."


In [41]:
sentences = [sent1, sent2]
vectorized_array = cv.fit_transform(sentences).toarray()

In [42]:
feature_names = cv.get_feature_names_out()

In [43]:
feature_names

array(['an', 'anime', 'as', 'attack', 'besieged', 'by', 'cities',
       'created', 'creatures', 'death', 'discovers', 'enormous',
       'follows', 'for', 'forced', 'gripping', 'hajime', 'have', 'high',
       'humanity', 'humanoid', 'in', 'is', 'isayama', 'known', 'light',
       'live', 'massive', 'named', 'note', 'notebook', 'on', 'protection',
       'school', 'set', 'student', 'supernatural', 'that', 'titan',
       'titans', 'to', 'walled', 'which', 'who', 'within', 'world',
       'yagami'], dtype=object)

In [44]:
vectorized_array[0]

array([0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0], dtype=int64)

In [45]:
# remove stop words
# remove dual
# perform cv

In [46]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [47]:
stopWords=set(stopwords.words('english'))
wordTokenize1=word_tokenize(sent1)
wordTokenize2=word_tokenize(sent2)
filtered_sentence1 = [w for w in wordTokenize1 if not w.lower() in stopWords]
filtered_sentence2 = [w for w in wordTokenize2 if not w.lower() in stopWords]


In [48]:
wordTokenize1

['Attack',
 'on',
 'Titan',
 ',',
 'created',
 'by',
 'Hajime',
 'Isayama',
 ',',
 'is',
 'a',
 'gripping',
 'anime',
 'set',
 'in',
 'a',
 'world',
 'besieged',
 'by',
 'enormous',
 'humanoid',
 'creatures',
 'known',
 'as',
 'Titans',
 ',',
 'which',
 'have',
 'forced',
 'humanity',
 'to',
 'live',
 'within',
 'massive',
 'walled',
 'cities',
 'for',
 'protection',
 '.']

In [49]:
wt1=[ps.stem(w) for w in wordTokenize1]
wt1

['attack',
 'on',
 'titan',
 ',',
 'creat',
 'by',
 'hajim',
 'isayama',
 ',',
 'is',
 'a',
 'grip',
 'anim',
 'set',
 'in',
 'a',
 'world',
 'besieg',
 'by',
 'enorm',
 'humanoid',
 'creatur',
 'known',
 'as',
 'titan',
 ',',
 'which',
 'have',
 'forc',
 'human',
 'to',
 'live',
 'within',
 'massiv',
 'wall',
 'citi',
 'for',
 'protect',
 '.']

In [50]:
filtered_sentence1

['Attack',
 'Titan',
 ',',
 'created',
 'Hajime',
 'Isayama',
 ',',
 'gripping',
 'anime',
 'set',
 'world',
 'besieged',
 'enormous',
 'humanoid',
 'creatures',
 'known',
 'Titans',
 ',',
 'forced',
 'humanity',
 'live',
 'within',
 'massive',
 'walled',
 'cities',
 'protection',
 '.']

In [51]:
text1=' '.join(filtered_sentence1)

In [52]:
text1

'Attack Titan , created Hajime Isayama , gripping anime set world besieged enormous humanoid creatures known Titans , forced humanity live within massive walled cities protection .'

In [53]:
text2=' '.join(filtered_sentence2)
text2

'Death Note anime follows high school student named Light Yagami discovers supernatural notebook .'

In [54]:
text1=ps.stem(text1)
textm=ps.stem(text2)
textm

'death note anime follows high school student named light yagami discovers supernatural notebook .'

In [55]:
x=['loved','loving']

In [56]:
y=[ps.stem(w) for w in x]
y

['love', 'love']

In [57]:
x={'tags':['Attack on Titan, created by Hajime Isayama, is a gripping anime set in a world besieged by enormous humanoid creatures known as Titans, which have forced humanity to live within massive walled cities for protection.','Death Note is an anime that follows a high school student named Light Yagami who discovers a supernatural notebook.','To check the list of stopwords you can type the following commands in the python shell.']}

In [58]:
dff=pd.DataFrame(x)

In [59]:
dff

tags
0  Attack on Titan, created by Hajime Isayama, is...
1  Death Note is an anime that follows a high sch...
2  To check the list of stopwords you can type th...

In [60]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [61]:
sw=set(stopwords.words("english"))

In [62]:
def removeStopWords(obj):
    wt=word_tokenize(obj)
    fs=[w for w in wt if not w.lower() in sw]
    fs1=[ps.stem(g) for g in fs]
    return ' '.join(fs1)

In [63]:
dff['tags']=dff['tags'].apply(removeStopWords)

In [64]:
dff['tags'][1]

'death note anim follow high school student name light yagami discov supernatur notebook .'

In [65]:
from nltk.stem.porter import PorterStemmer
pss=PorterStemmer()

In [66]:
pss.stem('fucked')

'fuck'

In [67]:
x=['fucked','fucking']
y=[pss.stem(e) for e in x]
y

['fuck', 'fuck']

In [68]:
dff

tags
0  attack titan , creat hajim isayama , grip anim...
1  death note anim follow high school student nam...
2  check list stopword type follow command python...

In [69]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=50)

In [70]:
vectorized_array1 = cv.fit_transform(dff['tags']).toarray()

In [71]:
vectorized_array1

array([[1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
        1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0]],
      dtype=int64)

In [72]:
feature_names1 = cv.get_feature_names_out()

In [73]:
feature_names1

array(['anim', 'attack', 'besieg', 'check', 'citi', 'command', 'creat',
       'creatur', 'death', 'discov', 'enorm', 'follow', 'forc', 'grip',
       'hajim', 'high', 'human', 'humanoid', 'isayama', 'known', 'light',
       'list', 'live', 'massiv', 'name', 'note', 'notebook', 'protect',
       'python', 'school', 'set', 'shell', 'stopword', 'student',
       'supernatur', 'titan', 'type', 'wall', 'within', 'world', 'yagami'],
      dtype=object)

In [74]:
vectorized_array1[1]

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [1]:
x=1
y=1
x==y

True

In [5]:
if 1==10:
    print('yes')
#print('-----')
else:
    print("no")

no


In [14]:
x=pd.read_csv('frds.csv')
x

name       home status  id
0  swag     jhinti   12th   1
1  sonu  nuapatana    NIT   4
2   sim   sarakana     PW   3
3   sup  nuapatana    NIT   4

In [22]:
x=['swag', 'sonu', 'sim']
def ch(n,l):
    if n in l:
        print('sss')
    else:
        print('fgd')

In [23]:
ch('simg',x)

fgd


In [24]:
x = ['swag', 'sonu', 'sim']

def ch(n, l):
    if n in l:
        print('sss')
    else:
        print('fgd')

ch('simuuu', x)


fgd


In [1]:
import numpy as np
import pandas as pd

In [3]:
x=pd.read_csv('frds.csv')
x

name       home status  id
0  swag     jhinti   12th   1
1  sonu  nuapatana    NIT   4
2   sim   sarakana     PW   3
3   sup   jasuapur    bse  10

In [7]:
y=pd.read_csv('tmdb5kPrePData.csv')
y.loc[0,'tags']

'22nd centuri , parapleg marin dispatch moon pandora uniqu mission , becom torn follow order protect alien civil . action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav stephenlang jamescameron'

In [11]:
x=[{'over':'bannn'},{'gf':'me'}]
y=[x[0]['over']]
y

['bannn']

In [12]:
x=['sonu sahoo','sup reet']
y=(lambda x:[i.replace(" ","") for i in x])
x=y(x)
x

['sonusahoo', 'supreet']

In [16]:
x=['s','o']
y=['n','u']
z=x+y
z

['s', 'o', 'n', 'u']

In [17]:
z=' '.join(z)
z

's o n u'

In [9]:
x=pd.read_csv('tmdb5kPrePData.csv')
x.tail()

movie_id                                title  \
4806    872585                          Oppenheimer   
4807    346698                               Barbie   
4808    615656                    Meg 2: The Trench   
4809    569094  Spider-Man: Across the Spider-Verse   
4810    697843                         Extraction 2   

                                                   tags  
4806  stori j. robert oppenheim ’ role develop atom ...  
4807  barbi ken time live color seemingli perfect wo...  
4808  exploratori dive deepest depth ocean dare rese...  
4809  reunit gwen staci , brooklyn ’ full-tim , frie...  
4810  task extract famili merci georgian gangster , ...